// English copy for the VARELO tokenized station landing page. Ported
// verbatim from `VARELO Tokenized Station.dc.html`'s `EN` object — content
// and structure unchanged, only moved out of the prototype's inline script.
import { A, B, C, OFF } from './colors';

export const EN = {
  langBtn: 'عربي',
  nav: [
    { href: '#structure', label: 'Structure' },
    { href: '#streams', label: 'Income' },
    { href: '#advantages', label: 'Advantages' },
    { href: '#platform', label: 'Platform' },
  ],
  hero: {
    kicker: 'VARELO · Dubai · A world first',
    title: 'The world’s first tokenized fuel station.',
    sub: 'One Dubai station. Three income streams — land rent, fuel income and non-fuel profit — held in one regulated SPV and distributed to token holders every month.',
    cta1: 'Explore stations',
    cta2: 'The three income streams',
    hint: 'Scroll — the camera flies to each business as you read',
  },
  concept: {
    kicker: '01 · The concept',
    title: 'Three income sources. One issuing SPV.',
    body: 'We tokenize a Dubai fuel station by placing three income sources under one issuing special purpose vehicle: the land and station building, the owner’s income from fuel sales on the site, and the non-fuel businesses — convenience store, car wash, lubricants and tenant services.',
    items: [
      { k: 'A', color: A, label: 'Land & station building' },
      { k: 'B', color: B, label: 'Owner fuel income' },
      { k: 'C', color: C, label: 'Non-fuel businesses' },
    ],
  },
  structure: {
    kicker: '02 · How it works',
    title: 'A ring-fenced structure, from title deed to token.',
    investors: 'Investors',
    investorsSub: 'Verified wallets · professional & retail',
    owner: 'Station owner',
    ownerSub: 'Retained stake + operational role',
    fractions: 'ERC-3643 fractions',
    vault: 'Vault contract',
    vaultSub: 'Locks the ERC-721 SPV Ownership NFT. Fixed supply of fractions minted against it.',
    holdco: 'HoldCo · issuing SPV',
    holdcoSub: 'Articles, title deed and fuel-company lease hashed into the NFT metadata.',
    propco: 'Land & station building. Receives land rent and fuel income.',
    opco: 'Store, car wash, lubricants and tenant services. Receives non-fuel profit.',
    fuelco: 'Fuel company',
    fuelcoSub: 'pays PropCo a fixed lease plus a per-litre fee or turnover rent.',
  },
  streamsIntro: {
    top: 'One monthly distribution',
    legs: [
      { k: 'A', name: 'Land rent', type: 'Contractual' },
      { k: 'B', name: 'Fuel income', type: 'Volume-linked' },
      { k: 'C', name: 'Non-fuel profit', type: 'Growth-linked' },
    ],
    safe: 'Three sources. No single point of failure.',
    dip: 'If one stream dips, the other two keep paying.',
    kicker: '03 · Income',
    title: 'Three streams, three risk profiles.',
    body: 'Contractual rent, volume-linked fuel income and growth-linked non-fuel profit — all from one site. Each stream has its own source, receiving entity and stability, so investors can see exactly where every dirham comes from.',
  },
  labels: { source: 'Source', entity: 'Receiving entity', stability: 'Stability' },
  streams: [
    {
      k: 'A',
      color: A,
      zone: 'plot',
      kicker: 'Stream A',
      name: 'Land rent',
      body: 'The fuel company leases the land and station building from PropCo under a fixed lease. It is the most predictable part of the income, and the land keeps its value even if operating income falls.',
      source: 'Fixed lease paid by the fuel company',
      entity: 'PropCo',
      stability: 'High, contractual',
      meter: [A, A, A],
    },
    {
      k: 'B',
      color: B,
      zone: 'fuel_highway',
      kicker: 'Stream B',
      name: 'Fuel income',
      body: 'The owner’s income from fuel sold on site comes into the structure through a per-litre fee or a turnover rent clause with the fuel company. It rises and falls with the litres pumped.',
      source: 'Per-litre fee or turnover rent clause from the fuel company',
      entity: 'PropCo',
      stability: 'Medium, volume linked',
      meter: [B, B, OFF],
    },
    {
      k: 'C',
      color: C,
      zone: 'car_wash_inside',
      kicker: 'Stream C',
      name: 'Non-fuel profit',
      body: 'Every non-fuel business on the forecourt runs inside OpCo. Its net profit is the growth engine of the token — and the part that varies most from month to month.',
      source: 'Net profit of store, car wash, lubes and tenant rent',
      entity: 'OpCo',
      stability: 'Low to medium, varies monthly',
      meter: [C, OFF, OFF],
    },
  ],
  cParts: [
    {
      zone: 'car_wash_inside',
      kicker: 'Stream C · 1 · Service',
      name: 'Car wash',
      body: 'The automated tunnel wash earns on every visit, independent of fuel volumes.',
      metric: 'Reported monthly: car washes',
    },
    {
      zone: 'auto_service',
      kicker: 'Stream C · 2 · Service',
      name: 'Lubricants & tyre service',
      body: 'Oil changes, lubricants and tyres sold through the service bays add higher-margin revenue per vehicle.',
      metric: 'Included in OpCo net profit',
    },
    {
      zone: 'atm_plaza',
      kicker: 'Stream C · 3 · Tenants',
      name: 'ATMs & tenant services',
      body: 'Bank, cash-deposit and crypto ATMs and other tenants on the site pay rent to OpCo — a steadier layer inside the non-fuel stream.',
      metric: 'Included in OpCo net profit: tenant rent',
    },
    {
      zone: 'mart',
      kicker: 'Stream C · 4 · Retail',
      name: 'Convenience store & mall',
      body: 'The 24/7 store, café and retail units turn every fuel stop into a basket. Trading profit and unit rent flow to OpCo.',
      metric: 'Reported monthly: store transactions',
    },
    {
      zone: 'ev_charging',
      kicker: 'Other services · Optional',
      name: 'EV fast charging',
      body: 'EV charging is an optional additional service on the site, ready as electric traffic grows.',
      metric: 'Optional service',
    },
  ],
  combined: {
    ledgers: [
      { k: 'A', name: 'Land rent', entity: 'PropCo' },
      { k: 'B', name: 'Fuel income', entity: 'PropCo' },
      { k: 'C', name: 'Non-fuel profit', entity: 'OpCo' },
    ],
    sep: 'Separate books · monthly report',
    kicker: 'Reporting',
    title: 'Accounted separately. Paid as one.',
    body: 'Each stream is accounted for separately and reported to investors every month. The token pays one combined distribution.',
    one: 'One monthly distribution',
  },
  advIntro: { kicker: '04 · Advantages', title: 'Built to work for the owner, the investor and the platform.' },
  adv: [
    {
      zone: 'family_park',
      kicker: 'For the station owner',
      title: 'Raise capital without selling the station.',
      items: [
        {
          h: 'Capital without a full sale',
          b: 'Sell part of the economic interest, keep a retained stake and stay involved in operations.',
        },
        {
          h: 'An alternative to bank debt',
          b: 'No covenants, fixed repayments or personal guarantees — distributions follow actual income.',
        },
        { h: 'A broader buyer base', b: 'Many smaller investors instead of a single buyer, which supports valuation.' },
        { h: 'A staged exit', b: 'Sell further tranches, or buy tokens back, without restructuring the company.' },
        {
          h: 'Institutional-grade structure',
          b: 'Ring-fenced entities and audited accounts make the asset easier to finance or sell later.',
        },
      ],
    },
    {
      zone: 'cafe',
      kicker: 'For investors',
      title: 'A hard asset that pays monthly.',
      items: [
        { h: 'Low entry ticket', b: 'Access an asset class that normally needs AED 12 million to 30 million.' },
        {
          h: 'Monthly income',
          b: 'Distributions every month, instead of the quarterly or annual payouts of most property investments.',
        },
        {
          h: 'Diversified income on one site',
          b: 'Contractual rent, volume-linked fuel income and growth-linked non-fuel profit.',
        },
        { h: 'A hard asset underneath', b: 'The land keeps its value even if operating income falls.' },
        {
          h: 'Transparency',
          b: 'Monthly stream-level reporting, with report hashes and every distribution recorded on-chain.',
        },
        {
          h: 'A regulated product',
          b: 'A DFSA-approved offering with audited accounts and disclosure — unlike informal property syndicates.',
        },
        {
          h: 'Potential liquidity',
          b: 'Transfers between verified holders and, once a licensed venue lists the token, secondary trading.',
        },
      ],
    },
    {
      zone: 'aerial',
      kicker: 'For the platform',
      variant: 'platform',
      repLabel: 'One template, reused',
      origin: 'Dubai Elite Oasis · station 1',
      rep: ['Station 2', 'Station 3', 'Station 4', 'Station N', 'Other income assets'],
      feeLabel: 'Recurring platform revenue',
      fees: ['Issuance fees', 'Annual administration', 'Distribution processing', 'Secondary trading'],
      firstH: 'First reference case',
      firstB: 'UAE fuel infrastructure tokenization',
      title: 'One station today. A template for many.',
      items: [
        {
          h: 'A reusable template',
          b: 'The legal structure, contracts, distribution engine and reporting can be reused for more stations and other income-producing assets.',
        },
        {
          h: 'Recurring revenue',
          b: 'Issuance fees, annual administration fees, distribution processing and secondary trading fees.',
        },
        { h: 'Market position', b: 'The first reference case in UAE fuel infrastructure tokenization.' },
      ],
    },
  ],
  platIntro: { kicker: '05 · Platform features', title: 'Compliance, custody and payouts — enforced in code.' },
  features: [
    {
      zone: 'atm_crypto',
      num: '5.1 · Token & compliance',
      variant: 'token',
      title: 'A permissioned ERC-3643 token.',
      lead: 'ERC-3643, the T-REX standard, was built for tokenizing real-world assets. Transfers are checked on-chain against identity and compliance rules before they settle.',
      lead2:
        'Only wallets with a verified ONCHAINID identity can hold or receive fractions — and jurisdictions, holder caps, retail limits and lock-ups are enforced on every transfer.',
      badges: ['ERC-3643', 'T-REX standard', 'Built for RWA'],
      pipe: ['Transfer', 'Identity', 'Compliance', 'Settles'],
      pillars: [
        { h: 'Permissioned transfers', b: 'Only verified identities can hold or receive the token.' },
        { h: 'Built-in compliance', b: 'The rules live in the token itself, checked before every transfer settles.' },
        { h: 'Recoverable tokens', b: 'Lost keys are recovered through identity re-verification to a new wallet.' },
      ],
      items: [],
    },
    {
      zone: 'atm_bank',
      num: '5.2 · Vault & fractionalization',
      variant: 'vault',
      title: 'The SPV, locked in a vault.',
      lead: 'Ownership of the SPV is one ERC-721 NFT. It sits in a vault contract, and a fixed supply of ERC-3643 fractions is minted against it.',
      nftLabel: 'SPV Ownership NFT',
      nftStd: 'ERC-721',
      hashes: ['HoldCo articles', 'Title deed', 'Fuel-company lease'],
      hashTag: 'hash',
      fracLabel: 'Fixed supply · ERC-3643 fractions',
      release: 'Release path',
      unlock: ['All fractions burned', 'Legal wind-down attested'],
      items: [],
    },
    {
      zone: 'atm_deposit',
      num: '5.3 · Distribution engine',
      variant: 'cycle',
      title: 'Every month, the same cycle.',
      lead: 'Income from Streams A, B and C is combined, smoothed and paid out to verified holders — one distribution, every month.',
      hub: ['Every', 'month'],
      nodes: [
        { n: '01', h: 'Combine', b: 'A + B + C income' },
        { n: '02', h: 'Smooth', b: 'Reserve evens out swings' },
        { n: '03', h: 'Pay', b: 'AED payment token or bank transfer' },
      ],
      note: 'Payout method to be confirmed. A defined policy covers unclaimed amounts.',
      items: [],
    },
    {
      zone: 'station_front',
      num: '5.4 · Investor dashboard',
      variant: 'dash',
      title: 'See the station, stream by stream.',
      lead: 'Everything an investor needs, in one place — live from the same books the monthly report is built on.',
      d: {
        tabs: ['Holdings', 'Streams', 'Metrics', 'Documents', 'Statements'],
        fractions: 'Your fractions',
        value: 'Value',
        history: 'Distribution history · 12 months',
        streams: ['Land rent', 'Fuel income', 'Non-fuel profit'],
        monthly: 'Monthly breakdown',
        metrics: ['Litres sold', 'Store transactions', 'Car washes'],
        docs: ['Offering document', 'Audits', 'Valuations', 'Monthly reports'],
        onchain: 'hash on-chain',
        stmt: 'Monthly statement',
        stmtBtn: 'Download PDF',
        illus: 'Illustrative preview',
      },
      items: [],
    },
  ],
  footer: {
    line: 'A first reference case in UAE fuel infrastructure tokenization.',
    legal:
      'Concept presentation. The offering described is subject to regulatory approval and final documentation. Nothing on this page is an offer to sell or a solicitation to buy securities.',
  },
};
